CREATE DATABASE IF NOT EXISTS pandashop;
USE pandashop;

GRANT ALL PRIVILEGES ON pandashop.* TO 'mysqluser';
GRANT FILE on *.* to 'mysqluser';


GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'mysqluser';

FLUSH PRIVILEGES;